build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "OpenSSL/1.1.1c"
    CONAN_USERNAME: "conan"
    CONAN_LOGIN_USERNAME: "conanbot"
    CONAN_CHANNEL: "release"
    CONAN_UPLOAD: "https://api.bintray.com/conan/conan-community/conan"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: "0"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_TOTAL_PAGES: 2
    CONAN_BUILD_POLICY: "outdated"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_ARCHS: x86
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MT

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
