# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  CONAN_PASSWORD: 1
jobs:
- job: windows2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      pip.exe install requests
      pip.exe freeze
      python api.py
- job: win2016
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      pip.exe install requests
      pip.exe freeze
      python api.py
- job: win2012r2
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - script: |
      pip.exe install requests
      pip.exe freeze
      python api.py

